In [1]:
import torch

In [2]:
torch.__version__

'2.2.2+cpu'

In [3]:
!pip install pytorch

Defaulting to user installation because normal site-packages is not writeable
  Using cached pytorch-1.0.2.tar.gz (689 bytes)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for pytorch
Failed to build pytorch


  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\SAMEER\AppData\Local\Temp\pip-install-e_ojo4tm\pytorch_ce7b9ed445b64d49b519d23b60397ea5\setup.py", line 15, in <module>
      raise Exception(message)
  Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch
ERROR: Could not build wheels for pytorch, which is required to install pyproject.toml-based projects


In [4]:
import numpy as np

In [5]:
lst = [3,4,5,6]
arr = np.array(lst)

In [6]:
arr

array([3, 4, 5, 6])

In [7]:
type(lst)

list

In [8]:
arr.dtype

dtype('int32')

## Convert Numpy To Pytorch Tensors 

In [9]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [10]:
tensors[:2]    # Slicing

tensor([3, 4], dtype=torch.int32)

In [11]:
tensors[2]    # Slicing

tensor(5, dtype=torch.int32)

In [12]:
tensors[1:4]    # Slicing

tensor([4, 5, 6], dtype=torch.int32)

In [13]:
# Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]=100

In [14]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [15]:
arr

array([  3,   4,   5, 100])

In [16]:
# Prevent this by using torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [17]:
tensor_arr[3] = 120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120], dtype=torch.int32)
[  3   4   5 100]


In [18]:
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [19]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [20]:
torch.cuda.is_available()      # NO GPU

False

In [21]:
torch.cpu.is_available()       # YES CPU

True